# Generated by Django 4.0.1 on 2022-01-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_url', models.CharField(max_length=150)),
                ('categories', models.CharField(max_length=150)),
                ('sub_categories', models.CharField(max_length=150)),
                ('headline', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('images', models.CharField(max_length=150)),
                ('news_detail', models.CharField(max_length=150)),
            ],
        ),
    ]
