# Generated by Django 4.0.1 on 2022-01-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_rename_newsdetails_newsdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('sub_categories', models.CharField(max_length=150)),
                ('headline', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('images', models.CharField(max_length=150)),
                ('news_detail', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='newsdetail',
        ),
    ]
