# Generated by Django 4.0.1 on 2022-01-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_news_delete_newsdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_detail',
            field=models.TextField(),
        ),
    ]
