# Generated by Django 4.0.1 on 2022-01-07 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_alter_news_headline_alter_news_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='sub_categories',
        ),
    ]
